### ISSUE TITLE
是否支持websocket？

### ISSUE THREAD

**Issue by anerg2046** [ouqiang/goproxy#1]
比如客户端请求ws://192.168.0.10/test,这是代理，然后代理请求wss://23.233.14.17/test

23.233.14.17 这个ip写死在代理里面

**Comment by anerg2046** [comment]
另外，你的事件处理，必须都写么？默认取代理那里会出错
`package main

import (
	"net/http"
	"time"

	"github.com/ouqiang/goproxy"
)

type EventHandler struct {
	goproxy.Delegate
}

func (e *EventHandler) BeforeResponse(ctx *goproxy.Context, resp *http.Response, err error) {
	if err != nil {
		return
	}
	// 修改response
}

func main() {
	proxy := goproxy.New(goproxy.WithDelegate(&EventHandler.BeforeRequest))
	server := &http.Server{
		Addr:         ":8080",
		Handler:      proxy,
		ReadTimeout:  1 * time.Minute,
		WriteTimeout: 1 * time.Minute,
	}
	err := server.ListenAndServe()
	if err != nil {
		panic(err)
	}
}
`

出错信息：
`2018/11/12 18:59:52 http: panic serving 127.0.0.1:54806: runtime error: invalid memory address or nil pointer dereference
goroutine 19 [running]:
net/http.(*conn).serve.func1(0xc00007ea00)
        /usr/local/Cellar/go/1.11.1/libexec/src/net/http/server.go:1746 +0xd0
panic(0x12799e0, 0x14cd5c0)
        /usr/local/Cellar/go/1.11.1/libexec/src/runtime/panic.go:513 +0x1b9
main.(*EventHandler).Finish(0xc00007d2d0, 0xc00009ae20)
        <autogenerated>:1 +0x32
panic(0x12799e0, 0x14cd5c0)
        /usr/local/Cellar/go/1.11.1/libexec/src/runtime/panic.go:513 +0x1b9
main.(*EventHandler).Connect(0xc00007d2d0, 0xc00009ae20, 0x13155e0, 0xc0001100e0)
        <autogenerated>:1 +0x2e
github.com/ouqiang/goproxy.(*Proxy).ServeHTTP(0xc000080ff0, 0x13155e0, 0xc0001100e0, 0xc00012e000)
        /data/go/src/github.com/ouqiang/goproxy/proxy.go:152 +0x104
net/http.serverHandler.ServeHTTP(0xc000082ea0, 0x13155e0, 0xc0001100e0, 0xc00012e000)
        /usr/local/Cellar/go/1.11.1/libexec/src/net/http/server.go:2741 +0xab
net/http.(*conn).serve(0xc00007ea00, 0x13157e0, 0xc0000882c0)
        /usr/local/Cellar/go/1.11.1/libexec/src/net/http/server.go:1847 +0x646
created by net/http.(*Server).Serve
        /usr/local/Cellar/go/1.11.1/libexec/src/net/http/server.go:2851 +0x2f5
`

**Comment by ouqiang** [comment]
1. 理论上可以实现，不过目前websocket只能盲转发
2. 如果自定了handler需要实现接口所有方法，goproxy.DefaultDelegate实现了接口所有方法，可以继承后覆盖相应方法。

**Comment by langhuihui** [comment]
golang哪来的继承

**Comment by jiangyd** [comment]
@anerg2046 ws，wss的代理搞出来了吗，同求

**Comment by jiangyd** [comment]
@ouqiang  websocket盲转怎么搞呢

**Comment by ouqiang** [comment]
已支持ws, wss
