### ISSUE TITLE
苹果设备https 失败。

### ISSUE THREAD

**Issue by zuozhehao** [ouqiang/goproxy#14]
苹果设备https 失败，已安装证书并信任，
PC端 curl 提示“curl: (35) schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - 吊销功能无法检查证书是否吊销。”

app使用代理日志： HTTPS解密, 握手失败: remote error: tls: unknown certificate

**Comment by ouqiang** [comment]
检查下你的根证书有没安装成功，#5

**Comment by zuozhehao** [comment]
> 检查下你的根证书有没安装成功，#5
证书安装成功的，和Charles的安装方法一样，使用Charles测试没问题。

**Comment by ouqiang** [comment]
1. 贴出你的代码及配置文件
2. 苹果设备访问提示的错误是什么

**Comment by zuozhehao** [comment]
@ouqiang 
```
// 实现证书缓存接口
type Cache struct {
    m sync.Map
}

func (c *Cache) Set(host string, cert *tls.Certificate) {
    c.m.Store(host, cert)
}
func (c *Cache) Get(host string) *tls.Certificate {
    v, ok := c.m.Load(host)
    if !ok {
        return nil
    }

    return v.(*tls.Certificate)
}

//

func main() {
    proxy := goproxy.New(goproxy.WithDecryptHTTPS(&Cache{}))
    server := &http.Server{
        Addr:         ":8080",
        Handler:      proxy,
        ReadTimeout:  1 * time.Minute,
        WriteTimeout: 1 * time.Minute,
    }
    err := server.ListenAndServe()
    if err != nil {
        panic(err)
    }
}
```
![111](https://user-images.githubusercontent.com/4464252/88743970-a7d11680-d178-11ea-8461-af3a6c9ca940.png)

![123](https://user-images.githubusercontent.com/4464252/88743943-9720a080-d178-11ea-87f3-ef92b03b9f32.png)

**Comment by ouqiang** [comment]
1. 你访问的网站是什么
2. 苹果设备访问提示的错误是什么

**Comment by zuozhehao** [comment]
> 1. 你访问的网站是什么
> 2. 苹果设备访问提示的错误是什么

@ouqiang 
1. 苹果设备直接使用默认浏览器打开百度。https://m.baidu.com
2. 提示`此链接非私人链接` ,此网站可能在冒充“m.baidu.com”来窃取您的个人或财务信息。您应回到之前的页面。...

**Comment by ouqiang** [comment]
点击查看此证书

**Comment by zuozhehao** [comment]
@ouqiang 
![121](https://user-images.githubusercontent.com/4464252/88760989-cba85280-d1a0-11ea-92d2-1f8bfed06897.png)

**Comment by ouqiang** [comment]
安装最新版本再试试

**Comment by zuozhehao** [comment]
> 安装最新版本再试试

好的我试试。

**Comment by zuozhehao** [comment]
@ouqiang 
可以正常浏览了，不过控制台都是

```
HTTPS解密, 握手失败: EOF

2020/07/29 14:24:04 dig.bdurl.net:443 - HTTPS解密, 读取客户端请求失败: read tcp 192.168.14.88:8080->192.168.16.172:49945: i/o timeout
```

**Comment by ouqiang** [comment]
读取超时，dig.bdurl.net如果不是你要访问的目标站点，可忽略。
