### ISSUE TITLE
设置auth 无效

### ISSUE THREAD

**Issue by zuozhehao** [ouqiang/goproxy#15]
设置了auth, 在苹果手机上不输入验证一样连接。
```
func (e *event) Auth(ctx *goproxy.Context, rw http.ResponseWriter) {

	basic := "Basic " + base64.StdEncoding.EncodeToString([]byte("username:password"))
	ctx.Req.Header.Add("Proxy-Authorization", basic)
}
```

**Comment by ouqiang** [comment]
你的使用方法可能是错误的，Proxy-Authorization是提供给代理服务器的，你设置了上级代理？

**Comment by zuozhehao** [comment]
> 你的使用方法可能是错误的，Proxy-Authorization是提供给代理服务器的，你设置了上级代理？

那可能我方法用错了，不过我在手机上设置了账号和密码，在Auth方法里获取不到。

**Comment by ouqiang** [comment]
Authorization  需要返回401状态码
Proxy-Authorization 需要返回407状态码
