### ISSUE TITLE
发现https报错

### ISSUE THREAD

**Issue by 1683728221** [ouqiang/goproxy#17]
我使用的是中间人代理，也就是你写的goproxy案例源码运行，结果遇到报错情况，我使用的是谷歌浏览器，访问的是12306.cn网址， 结果12306.cn访问正常，但是有以下报错信息，这是为什么，我猜测是证书问题吧，因为提示的信息是https解密失败，报错信息如下：
2020/08/18 03:47:53 https://clients2.googleusercontent.com/crx/blobs/QgAAAC6zw0qH2DJtnXe8Z7rUJP29CWJ9zeWEcj3GGPrivl5tRubHNgYOBQPoXgda7uGVr60dRxJXFGZEMk8k1Z-T_DzUV57zZqwo0SnuHBZ3mW5
SAMZSmuUXlXeR0eto3WFshPzEgLgRTnTIKQ/extension_6_38_2_0.crx - HTTPS解密, 请求错误: dial tcp 172.217.24.1:443: i/o timeout

**Comment by ouqiang** [comment]
连接超时，访问谷歌的域名，你有FQ吗
