### ISSUE TITLE
https证书问题： NET::ERR_CERT_VALIDITY_TOO_LONG

### ISSUE THREAD

**Issue by li45** [ouqiang/goproxy#19]
![image](https://user-images.githubusercontent.com/6301741/94324335-00cbf800-ffcc-11ea-8465-f20746e5e012.png)
查了下网上有人说是证书有效期太长，不能超过39个月

https://support.servertastic.com/knowledgebase/article/neterr_cert_validity_too_long-the-server-certificate-has-a-validity-period-that-is-too-long
![image](https://user-images.githubusercontent.com/6301741/94324381-44befd00-ffcc-11ea-9c10-1edaf23be58b.png)

**Comment by ouqiang** [comment]
证书默认有效期已调整为1年
