### ISSUE TITLE
想问下怎么解密https响应包？

### ISSUE THREAD

**Issue by shadow1ng** [ouqiang/goproxy#26]
proxy := goproxy.New(goproxy.WithDecryptHTTPS(&Cache{}))
ctx.Req = tlsReq
fmt.Println(ctx.Req)
body, err := ioutil.ReadAll(ctx.Req.Body)
fmt.Println(string(body),err)
ctx.Req.Body = ioutil.NopCloser(bytes.NewReader(body))
这个能获取https明文请求包了。

但https的响应包怎么获取？

body, err := ioutil.ReadAll(resp.Body)
fmt.Println(string(body),err)
resp.Body = ioutil.NopCloser(bytes.NewReader(body))
err = resp.Write(tlsClientConn)
获取到的响应包是密文的

**Comment by ouqiang** [comment]
看下这个"密文"是不是使用了gzip压缩。

**Comment by shadow1ng** [comment]
OK了，后面我新增了一个函数调用WithDelegate+WithDelegatetHTTPS，这样就能在https里的BeforeResponse中查看解密后的内容了

**Comment by nvv5** [comment]
@shadow1ng 大佬，可以分享下你的解决方法吗？是在BeforeResponse里加什么吗？我怎么改也是乱码

**Comment by shadow1ng** [comment]
> @shadow1ng 大佬，可以分享下你的解决方法吗？是在BeforeResponse里加什么吗？我怎么改也是乱码

新建一个函数，把https和WithDecryp结合在一起,就行
```
// WithDecryptHTTPS 中间人代理, 解密HTTPS, 需实现证书缓存接口
func WithDelegatetHTTPS(c cert.Cache, delegate Delegate) Option {
	return func(opt *options) {
		opt.decryptHTTPS = true
		opt.certCache = c
		opt.delegate = delegate
	}
}
proxy := client.New(client.WithDelegatetHTTPS(&Cache{}, &EventHandler{}))
	server := &http.Server{....}
```

**Comment by ouqiang** [comment]
goproxy.New方法本身支持的是可变参数，直接传入多个参数即可。
