### ISSUE TITLE
两个问题，wss如何进行转发，BeforeRequest如何在该方法内自定义返回

### ISSUE THREAD

**Issue by fenglindubu** [ouqiang/goproxy#27]
1、wss如何进行转发，能否进行优化
2、由于https Connect 、Auth无法获取请求的具体地址
     BeforeRequest 如何在该方法内自定义返回内容，例如返回302重定向、404、200等

**Comment by ouqiang** [comment]
1. 已支持ws, wss
2. https Connect 、Auth方法中使用rw自定义返回内容

**Comment by fenglindubu** [comment]
感谢回答！
