### ISSUE TITLE
https解密失败

### ISSUE THREAD

**Issue by hxfighting** [ouqiang/goproxy#3]
HTTPS解密, 请求错误: proxyconnect tcp: dial tcp :0: connect: can't assign ted address

本地已信任并安装该证书。

**Comment by hxfighting** [comment]
解密结果也是乱码的
![image](https://user-images.githubusercontent.com/26914712/62816709-ef245880-bb5d-11e9-9b1c-1825f5d6a705.png)

**Comment by ouqiang** [comment]
代码方便贴出来看下吗

**Comment by hxfighting** [comment]
已解决，gzip压缩导致乱码
