### ISSUE TITLE
HTTPS中，在BeforeResponse中修改response header时，Content-Length无法修改

### ISSUE THREAD

**Issue by candicandi** [ouqiang/goproxy#30]
HTTPS中，在BeforeResponse中修改response header时，Content-Length无法修改，在原连接为http时是正常的，但是一旦原连接为https，则其他header的增删改都没有，唯有Content-Length无法修改，设置后也是原来的

**Comment by ouqiang** [comment]
Content-Length自动计算的，不支持修改。
