### ISSUE TITLE
remote error: tls: unknown certificate

### ISSUE THREAD

**Issue by jiangyd** [ouqiang/goproxy#5]
remote error: tls: unknown certificate，这个错误是啥意思
if err := tlsClientConn.Handshake(); err != nil {
		fmt.Println(err)
		return
	}

**Comment by ouqiang** [comment]
客户端证书有问题，要看下具体的上下文才能判断

**Comment by jiangyd** [comment]
![图片](https://user-images.githubusercontent.com/13939319/67060172-62fe6500-f18e-11e9-843b-9bcc6d18112c.png)
1. 比如我访问一个网址（浏览器提示不安全，我点继续访问，需要点好几下才行），
2. 这个网址有ajax请求各种域名，全是这样不能访问的，需要把请求链接拷贝出来再浏览器访问一遍（确认继续访问才行）
我使用其它代理服务器jmeter 没这样的情况

**Comment by jiangyd** [comment]
附上使用jmeter录制代理，同样导入根证书到系统，为什么用jmeter，访问网站锁是绿的
![图片](https://user-images.githubusercontent.com/13939319/67060595-20d62300-f190-11e9-9859-454858637dbd.png)

**Comment by ouqiang** [comment]
忽略证书校验试试

**Comment by jiangyd** [comment]
![图片](https://user-images.githubusercontent.com/13939319/67061038-8ecf1a00-f191-11e9-9d02-65a45743ff25.png)

![图片](https://user-images.githubusercontent.com/13939319/67061078-aefed900-f191-11e9-9b2f-836dfb6951ab.png)

**Comment by ouqiang** [comment]
根证书没安装成功

**Comment by jiangyd** [comment]
没修改你的代码，证书是安装成功了，可能是根证书不是动态生成的，jmeter是动态生成的，有7天过期时间
你是不是可以搞个，在运行环境生成这些信息呢

**Comment by jiangyd** [comment]
或者说，你本地没遇到这个问题?,你可以换个电脑试试

**Comment by ouqiang** [comment]
跟过期时间没关系，我和我同事都有使用哈

**Comment by ouqiang** [comment]
你可以先在手机上测试，手机上安装根证书比较简单，看下https是否正常

**Comment by ouqiang** [comment]
<img width="886" alt="截屏2019-10-1823 01 10" src="https://user-images.githubusercontent.com/12163055/67105491-73005e00-f1fb-11e9-8049-b33cbf7f7f89.png">

**Comment by jiangyd** [comment]
问题已解决，我系统重启了就正常，Mac信任证书，系统要重启才会真的生效
