### ISSUE TITLE
在Firefox使用代理会出现建立安全连接失败的情况

### ISSUE THREAD

**Issue by jiangyd** [ouqiang/goproxy#6]
![image](https://user-images.githubusercontent.com/13939319/67077604-2cdad880-f1c2-11e9-94f8-e69ba577b742.png)

我按照此错误，网上搜索了下，删除cert8.db没有效果，换其他代理服务器可以访问

**Comment by ouqiang** [comment]
排查下是所有客户端都连接异常，还是只有Firefox

1. 使用其他浏览器设置代理访问是否正常
2. 使用curl设置代理访问是否正常

<img width="879" alt="截屏2019-10-1823 07 53" src="https://user-images.githubusercontent.com/12163055/67106272-d8088380-f1fc-11e9-918f-5884f29ba125.png">

**Comment by jiangyd** [comment]
Firefox重置了，正常显示
