### ISSUE TITLE
x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by jiangyd** [ouqiang/goproxy#7]
![图片](https://user-images.githubusercontent.com/13939319/67173761-48c4c100-f3f2-11e9-82e0-2c226073c1f6.png)

报这个错误，这个是有的网站才会报，同样使用jmeter代理正常
x509: certificate signed by unknown authority ggglll

**Comment by ouqiang** [comment]
服务端提供的证书无效，比如自签名证书
需要代码里配置忽略证书校验

**Comment by jiangyd** [comment]
我不用代理，访问这个网址，显示锁的图是绿色的，证书是有效的

**Comment by ouqiang** [comment]
网址发出来看下

**Comment by jiangyd** [comment]
我公司内部的你估计访问不了,  https://jira.jiagouyun.com

**Comment by jiangyd** [comment]
![图片](https://user-images.githubusercontent.com/13939319/67176928-bd9df800-f3fe-11e9-809b-c04c2bd637f6.png)

**Comment by ouqiang** [comment]
公司内部的是自签证书吧

**Comment by jiangyd** [comment]
如果要忽略服务端证书在哪里改代码，我先试试看看

**Comment by jiangyd** [comment]
![图片](https://user-images.githubusercontent.com/13939319/67177441-1d959e00-f401-11e9-9ba7-bb8d9f1da5bc.png)
，我这样式是没有效果

**Comment by jiangyd** [comment]
有没有可能是开启了双向认证呢?,如果这种情况怎么搞

**Comment by jiangyd** [comment]
我自己自签然后模拟了这个现象，至于我公司的jira,还有confluence为什么自签不代理访问锁是绿的，这个情况就不清楚了
然后请教下，现在如何解决这个问题呢，忽略服务端证书代码咋搞

**Comment by jiangyd** [comment]
已解决
transport := http.Transport{
		TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
	}
